services:
  - type: web
<<<<<<< HEAD
    name: ai-language-translator
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
=======
    name: flask-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
>>>>>>> 45a39fa1ef725379d9b0eb9670c85de51998b0c5
